### PR TITLE
Refactored processing example to match Open frameworks example

### PR DESCRIPTION
**Pull request by gnastacast**
This still needs to detect other communicating nodes as right now it only acts as a master node to itself. The reason for this is because it was ambiguous whether knownIDs was meant to be an array of integer IDs or seconds elapsed from their last communication. Also neither the status nor the control listeners have been tested.

### CODE REVIEW

**Comment by workergnome** [comment]
Hi there, Nico!  I'll look at this tonight, once I'm not working on my actual job.

**Comment by gnastacast** [comment]
Cool! I also made a version in Unity. Once this is done I'll open another pull request for it.

**Comment by workergnome** [comment]
Lovely.  Want to open an issue for the documentation about "whether knownIDs was meant to be an array of integer IDs or seconds elapsed from their last communication."?  (It's an array of integer IDs)

**Comment by gnastacast** [comment]
As far and I can tell it is actually meant to be both. I added a new object for the ID's that has both ID and timestamp in the last commit.

**Comment by gnastacast** [comment]
I think the only thing left for the processing example is to decide how to add all the IP addresses. Is that something we'd do manually?

Edit: I forgot I still have to enforce the CMAX rule.

Edit2: Should things like the IP addresses and the ID be passed to the DonutCop object rather than being declared? That way people don't have to touch the DonutCop object at all.

**Comment by workergnome** [comment]
Hey, @gnastacast — I just realized that all my emails to you have been bouncing back, and ending up in my spam.  Which explains why you don't answer them.  Want to sit down sometime and get this integrated?  (And do you have another email that my gmail account doesn't reject for dumb reasons?)

**Comment by gnastacast** [comment]
Oh shit yeah it looks like my email server is down. When should we meet I
am in delaware right now. This email will work while I get my server back
up.

Nico

**Comment by gnastacast** [comment]
gnastacast@gmail.com

**Pull request merged**
